config/routes.rb
Rails.application.routes.draw do
  #admin認証機能
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  #end_user認証機能
  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  #ルートパス
  root to:'public/homes#top'
  
  #admin用パス
  namespace :admin do
    resources :end_users, only: [:show, :index, :edit, :update]
    resources :posts, only: [:show, :index, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index, :destroy]
    #ユーザー検索機能
    get 'search'=> 'searches#search'
    get "search_tag" => "posts#search_tag"
    #コメント一覧表示
    get "comments"=> "comments#comments_all"
    get "images"=> "posts#images"
  end
  
  #end_user用パス
  scope module: :public do
    resources :posts do
      resource :favorite_posts, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    #退会機能
    get  'end_users/confirm_withdraw' => 'end_users#confirm_withdraw'
    patch  'end_users/withdraw' => 'end_users#withdraw'
    resources :end_users, only: [:show, :edit, :update] do
      member do
        get :favorite_posts
      end
    end
    get 'search'=> 'searches#search'
    get "search_tag" => "posts#search_tag"
    get "images"=> "posts#images"
  end
  #ゲストログイン用パス
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_and_tags,dependent: :destroy
  has_many :posts, through: :post_and_tags

  validates :tag_name, presence:true, length:{maximum:20}
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tags = Tag.page(params[:page]).per(20).order(created_at: :desc) 
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: "タグを削除しました。"
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-sm-6 mx-auto">
      <p><%= flash[:notice] %></p>
      <h2>タグ一覧</h2>
        <table class="table table-border">
          <thead>
            <tr>
              <th>タグ</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @tags.each do |tag| %>
            <tr>
              <td class="align-middle"><%=link_to tag.tag_name,admin_search_tag_path(tag_id: tag.id) %> <%="(#{tag.posts.count})" %></td>
              <td class="text-center">
                <%= link_to "削除", admin_tag_path(tag.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当にタグを削除しますか?" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @tags %>
    </div>
  </div>
</div>