config/routes.rb
Rails.application.routes.draw do
  #admin認証機能
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  #end_user認証機能
  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  #ルートパス
  root to:'public/homes#top'
  
  #admin用パス
  namespace :admin do
    resources :end_users, only: [:show, :index, :edit, :update]
    resources :posts, only: [:show, :index, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index, :destroy]
    #ユーザー検索機能
    get 'search'=> 'searches#search'
    get "search_tag" => "posts#search_tag"
    #コメント一覧表示
    get "comments"=> "comments#comments_all"
    get "images"=> "posts#images"
  end
  
  #end_user用パス
  scope module: :public do
    resources :posts do
      resource :favorite_posts, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    #退会機能
    get  'end_users/confirm_withdraw' => 'end_users#confirm_withdraw'
    patch  'end_users/withdraw' => 'end_users#withdraw'
    resources :end_users, only: [:show, :edit, :update] do
      member do
        get :favorite_posts
      end
    end
    get 'search'=> 'searches#search'
    get "search_tag" => "posts#search_tag"
    get "images"=> "posts#images"
  end
  #ゲストログイン用パス
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :end_user
  has_many :favorite_posts,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :post_and_tags,dependent: :destroy
  has_many :tags, through: :post_and_tags

  has_many_attached :images
  #画像の制限
  validate :images_length

  with_options presence: true do
     validates :end_user_id
     validates :body
  end
  validates :body,length:{maximum:500}

  def post_favorited_by?(end_user)
    favorite_posts.where(end_user_id: end_user.id).exists?
  end

  #タグの保存
  def save_tags(tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tag_name:old_name)
    end
    # 新しいタグを保存
    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(tag_name:new_name)
      self.tags << tag
    end
  end

  private
  #画像の枚数制限
  def images_length
    if images.length > 6
      errors.add(:images, "は6枚以内にしてください")
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
    @post_tags = @post.tags
    @comment = @post.comments
  end

  def index
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc) 
  end

  def images
    #1ページあたり投稿10件分の画像
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc) 
  end

  def edit
     @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: "投稿を削除しました"
  end

  def search_tag
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.order(created_at: :desc) 
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(10)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_comment.html.erb
<!--posts/showで使用-->
<table>
  <tbody>
    <% post.comments.each do |comment| %>
    <tr>
      <td class="col-1">
        <%= link_to admin_end_user_path(comment.end_user) do %>
          <%= image_tag comment.end_user.get_profile_image, size: "50x50" %><br>
          <%= comment.end_user.name %>
        <% end %>
      </td>
      <td class="comment_cell pl-3 col-5">
        <span class="comment_created"><%= comment.created_at.strftime('%Y/%m/%d/%H:%M') %></span></br>
        <span class="comment_width"><%= comment.comment %></span>
      </td>
      <td class="pl-3 col-1">
        <%= link_to admin_post_comment_path(comment.post, comment), method: :delete, data: { confirm: '本当に削除しますか？' } do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
   </tbody>
</table>

app/views/admin/posts/images.html.erb
<div class='container px-sm-0'>
<%= flash[:notice] %>
  <div class="col-12 mx-auto">
    <h2 class="mt-3">投稿画像一覧</h2>
    <% @posts.each do |post| %>
      <% post.images.each do |image| %>
        <%= link_to admin_post_path(post.id) do %>
          <%= image_tag image, size: "180x180", class:"post_img" %>
        <% end %>
      <% end %>
    <% end %>
    <%= paginate @posts %>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= flash[:notice] %>
  <div class="col-12 mx-auto">
    <div class="d-flex mt-3">
      <h2>投稿一覧</h2>
      <h4 class="mt-2 ml-3"><%= link_to "画像一覧", admin_images_path %></h4>
    </div>
    <%= render 'admin/shared/post_index', posts: @posts %>
    <%= paginate @posts %>
  </div>
</div>

app/views/admin/posts/search_tag.html.erb
<div class="container">
  <div class="d-flex">
    <h2> <i class="fa-sharp fa-solid fa-tag"></i><%= @tag.tag_name %> 一覧</h2>
    <span class="ml-3 mt-2">(全<%= @tag.posts.count %>件)</span>
  </div>
  <%= render 'admin/shared/post_index', posts: @posts %>
  <%= paginate @posts %>
</div>

app/views/admin/posts/show.html.erb
<div class='container'>
  <%= flash[:notice] %>
  <div class="d-flex">
    <h2 class="mt-3">投稿詳細</h2>
    <!--削除リンク-->
      <div class="pl-5 mt-4">
        <span class="mt-4 ml-5"><%= link_to "削除", admin_post_path(@post), data: { confirm: '本当に削除しますか？' }, class:"btn btn-sm btn-danger", method: :delete %></span>
      </div>
  </div>
  <!--投稿情報-->
  <div class='row'>
    <div class="col-sm-10 col-md-6 mx-auto mt-2">
      <p><b>投稿者 : 
            <%= link_to admin_end_user_path(@post.end_user_id) do %>
              <%= image_tag @post.end_user.get_profile_image, size:"30x30" %>
              <%= @post.end_user.name %>
            <% end %>
      </b></p>
      <p><b>投稿日 : <%= @post.created_at.strftime('%Y/%m/%d/%H:%M') %></b></p>
      <p><b>タグ : 
          <% @post_tags.each do |tag| %>
            <i class="fa-sharp fa-solid fa-tag"></i>
            <%= link_to tag.tag_name,admin_search_tag_path(tag_id: tag.id) %>
          <% end %> 
      </b></p>
      <p class="w-100 border border-dark p-2"><%= safe_join(@post.body.split("\n"),tag(:br)) %></p>
    </div>
    
  <!--画像の表示-->
    <div class="col-sm-10 col-md-5 mx-auto">
      <% if @post.images.attached? %>
      <h4 class="mt-3">画像</h4>
        <% @post.images.each do |image| %>
          <%= link_to image, "data-lightbox": image do %>
            <%= image_tag image, size: "200x200", class:"post_img" %>
          <% end %>
        <% end %>
      <% else %>
      <% end %>
    </div>
   </div>
   
  <!--コメントエリア-->
  <div class="col-12 mx-auto mt-3">
    <h4>コメント</h4>
      <% unless @comment.present? %>
        <div>
          <p>コメントはありません</p>
        </div>
      <% end %>
    <div id="comment-destroy">
      <%= render 'comment', post: @post, comment: @comment %>
    </div>
  </div>

</div>