config/routes.rb
Rails.application.routes.draw do
  #admin認証機能
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  #end_user認証機能
  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  #ルートパス
  root to:'public/homes#top'
  
  #admin用パス
  namespace :admin do
    resources :end_users, only: [:show, :index, :edit, :update]
    resources :posts, only: [:show, :index, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index, :destroy]
    #ユーザー検索機能
    get 'search'=> 'searches#search'
    get "search_tag" => "posts#search_tag"
    #コメント一覧表示
    get "comments"=> "comments#comments_all"
    get "images"=> "posts#images"
  end
  
  #end_user用パス
  scope module: :public do
    resources :posts do
      resource :favorite_posts, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    #退会機能
    get  'end_users/confirm_withdraw' => 'end_users#confirm_withdraw'
    patch  'end_users/withdraw' => 'end_users#withdraw'
    resources :end_users, only: [:show, :edit, :update] do
      member do
        get :favorite_posts
      end
    end
    get 'search'=> 'searches#search'
    get "search_tag" => "posts#search_tag"
    get "images"=> "posts#images"
  end
  #ゲストログイン用パス
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorite_posts, dependent: :destroy
  has_many :favorite_images, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :email, uniqueness: true

  validates :introduction,length:{maximum:50}

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.name="ゲスト"
      end_user.is_deleted="false"
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  #admin側検索方法:部分一致
  def self.search_for(word)
    EndUser.where(['name LIKE ? OR email Like ?', '%'+word+'%', '%'+word+'%'])
  end
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @end_users = EndUser.order(created_at: :desc) 
    @end_users = Kaminari.paginate_array(@end_users).page(params[:page]).per(10)
  end

  def show
    @end_user = EndUser.find(params[:id])
    @posts = @end_user.posts.page(params[:page]).per(5).order(created_at: :desc)
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admin_end_user_path(@end_user), notice: "更新しました"
    else
      render :edit
    end
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name, :email, :is_deleted)
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<div class="container">
  <h4 class="mb-4"><%= @end_user.name %>さんのユーザー情報編集</h4>
    <%= render 'admin/shared/error_messages', resource: @end_user %>
      <table class="table table-bordered col-8">
      <%= form_with model: @end_user, url: admin_end_user_path(@end_user), method: :patch do |f| %>
        <tr>
          <td class="col-4">ユーザーID</td>
          <td><%= @end_user.id %></td>
        </tr>
        <tr>
          <td><%= f.label "ユーザー名" %></td>
          <td><%= f.text_field :name, autoforcus: true, autocomplete: "name", class:"w-100" %></td>
        </tr>
        <tr>
          <td><%= f.label "メールアドレス" %></td>
          <td><%= f.text_field :email, autoforcus: true, autocomplete: "email", class:"w-100" %></td>
        </tr>
        <tr>
          <td><%= f.label "会員ステータス" %></td>
          <td>
            <span>
              <%= f.radio_button(:is_deleted, false) %>
              <%= f.label(:is_deleted, "有効", value: "false") %>
            </span>
            <span class="pl-4">
              <%= f.radio_button(:is_deleted, true) %>
              <%= f.label(:is_deleted, "退会", value: "true") %>
            </span>
          </td>
        </tr>
      </table>
      <div>
        <% if @end_user.email != "guest@example.com" %>
          <%= f.submit "更新する", class: "btn btn-success" %>
        <% else %>
          <p>ゲストユーザーの情報は変更できません</p>
        <% end %>
      </div>
      <% end %>
</div>

app/views/admin/end_users/index.html.erb
<div class='container'>
<%= flash[:notice] %>
  <div>
    <h2>ユーザー一覧</h2>
      <%= render 'admin/shared/end_user_index', end_users: @end_users %>
      <%= paginate @end_users %>
  </div>
</div>

app/views/admin/end_users/show.html.erb
<div class="container">
  <%= flash[:notice] %>
  <div class="mt-2">
    <h4><%= @end_user.name %>さんのユーザー詳細</h4>
    <div class="row"> 
      <div class="col-md-10 col-lg-5 mx-auto">
        <table class="table table-bordered">
          <tr>
            <td>会員ID</td>
          　<td><%= @end_user.id %></td>
          </tr>
          <tr>
            <td>ユーザー名</td>
            <td><%= @end_user.name %></td>
          </tr>
          <tr>
            <td>イントロダクション</td>
            <td><%= @end_user.introduction %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @end_user.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td class="<%= @end_user.is_deleted ? 'text-secondary' : 'text-success' %>"><%= @end_user.is_deleted ? '退会済み' : '有効' %></td>
          </tr>
        </table>
        <% if @end_user.email != "guest@example.com" %>
          <%= link_to "編集", edit_admin_end_user_path(@end_user), class: "btn btn-success edit_user_#{@end_user.id}" %> 
        <% else %>
          <p class="mb-3">ゲストユーザーの情報は変更できません</p>
        <% end %>
      </div>
      <!--ユーザーの投稿一覧-->
      <div class="col-md-10 col-lg-7 mt-3 mx-auto">
        <%= render 'admin/shared/post_index', posts: @posts %>
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>