config/routes.rb
Rails.application.routes.draw do
  #admin認証機能
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  #end_user認証機能
  devise_for :end_users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  #ルートパス
  root to:'public/homes#top'
  
  #admin用パス
  namespace :admin do
    resources :end_users, only: [:show, :index, :edit, :update]
    resources :posts, only: [:show, :index, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index, :destroy]
    #ユーザー検索機能
    get 'search'=> 'searches#search'
    get "search_tag" => "posts#search_tag"
    #コメント一覧表示
    get "comments"=> "comments#comments_all"
    get "images"=> "posts#images"
  end
  
  #end_user用パス
  scope module: :public do
    resources :posts do
      resource :favorite_posts, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    #退会機能
    get  'end_users/confirm_withdraw' => 'end_users#confirm_withdraw'
    patch  'end_users/withdraw' => 'end_users#withdraw'
    resources :end_users, only: [:show, :edit, :update] do
      member do
        get :favorite_posts
      end
    end
    get 'search'=> 'searches#search'
    get "search_tag" => "posts#search_tag"
    get "images"=> "posts#images"
  end
  #ゲストログイン用パス
  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :end_user
  belongs_to :post

  validates :comment,length:{maximum:200}

  with_options presence: true do
     validates :comment
     validates :end_user_id
     validates :post_id
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorite_posts, dependent: :destroy
  has_many :favorite_images, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :email, uniqueness: true

  validates :introduction,length:{maximum:50}

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.name="ゲスト"
      end_user.is_deleted="false"
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  #admin側検索方法:部分一致
  def self.search_for(word)
    EndUser.where(['name LIKE ? OR email Like ?', '%'+word+'%', '%'+word+'%'])
  end
end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
  belongs_to :end_user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :end_user_id

  with_options presence: true do
     validates :end_user_id
     validates :post_id
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :end_user
  has_many :favorite_posts,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :post_and_tags,dependent: :destroy
  has_many :tags, through: :post_and_tags

  has_many_attached :images
  #画像の制限
  validate :images_length

  with_options presence: true do
     validates :end_user_id
     validates :body
  end
  validates :body,length:{maximum:500}

  def post_favorited_by?(end_user)
    favorite_posts.where(end_user_id: end_user.id).exists?
  end

  #タグの保存
  def save_tags(tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tag_name:old_name)
    end
    # 新しいタグを保存
    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(tag_name:new_name)
      self.tags << tag
    end
  end

  private
  #画像の枚数制限
  def images_length
    if images.length > 6
      errors.add(:images, "は6枚以内にしてください")
    end
  end
end

app/models/post_and_tag.rb
class PostAndTag < ApplicationRecord
  belongs_to :tag
  belongs_to :post

  with_options presence: true do
     validates :post_id
     validates :tag_id
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_and_tags,dependent: :destroy
  has_many :posts, through: :post_and_tags

  validates :tag_name, presence:true, length:{maximum:20}
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to request.referer, notice: "削除しました"
  end

  def comments_all
    @comments = Comment.all.order(created_at: :desc) 
    @comments = Kaminari.paginate_array(@comments).page(params[:page]).per(20)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
    @post_tags = @post.tags
    @comment = @post.comments
  end

  def index
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc) 
  end

  def images
    #1ページあたり投稿10件分の画像
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc) 
  end

  def edit
     @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path, notice: "投稿を削除しました"
  end

  def search_tag
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.order(created_at: :desc) 
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(10)
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    if params[:word].present?
      @word = params[:word]
      @records = EndUser.search_for(@word)
      @result = Kaminari.paginate_array(@records).page(params[:page]).per(10)
    else
      redirect_to admin_end_users_path, notice:"キーワードを入力してください"
    end
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tags = Tag.page(params[:page]).per(20).order(created_at: :desc) 
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path, notice: "タグを削除しました。"
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  private
    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_posts_path
      else
        posts_path
      end
    end

    def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :user
        root_path
      elsif resource_or_scope == :admin
        new_admin_session_path
      else
        root_path
      end
    end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_end_user_index.html.erb
<!--end_users/index, searches/searchで使用-->
<table class='table'>
  <thead>
    <tr>
      <th class="col-1 text-center">ID</th>
      <th class="col-3 text-center">プロフィール画像</th>
      <th>ユーザー名</th>
      <th>アドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% end_users.each do |end_user| %>
    <tr>
      <td class="text-center">
        <%= end_user.id %><br/>
      </td>
      <td class="text-center"><%= image_tag end_user.get_profile_image, size: '50x50' %></td>
      <td><%= link_to admin_end_user_path(end_user.id) do %><%= end_user.name %><% end %></td>
      <td><%= end_user.email %></td>
      <td class= "<%= end_user.is_deleted ? 'text-secondary' : 'text-success' %>"><%= end_user.is_deleted ? '退会済み' : '有効' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/admin/shared/_post_index.html.erb
<!--end_users/show, posts/index, posts/search_tagで使用-->
<% posts.each do |post| %>
<div class="card border-dark my-2 col-sm-12 col-md-10 mx-auto">
  <div class="card-body">
    <div class="d-flex">
        <span><%= link_to admin_end_user_path(post.end_user.id) do %><%= image_tag post.end_user.get_profile_image, size:'30x30' %></span>
      <span class="mt-3 ml-3"><%= post.end_user.name %></span>
      <% end %>
    </div>
    <%= link_to admin_post_path(post.id), class:"text-dark" do %>
    <div>
      <span><%= post.created_at.strftime('%Y/%m/%d') %>  <%= post.created_at.strftime('%H:%M') %></span>
      <p class="mb-0"><%= post.body.truncate(100) %></p>
    </div>
    <!--画像-->
    <% if post.images.present? %>
    <div class="photo_area">
      <% post.images.each do |image| %>
        <%= image_tag image, size: "100x50", class:"post_index_img" %>
      <% end %>
    </div>
    <% end %>
    <% end %>
    <div class="index_option">
      <span id="comment_count"><%= post.comments.count %>コメント</span>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_header.html.erb
<div class="d-flex py-2 px-3">
  <!--ロゴ--> 
  <div>
    <%= link_to root_path do %>
      <%= image_tag 'logo.png', :size => '170x50' %>
    <% end %>
  </div>
　<!--ようこそ-->
  <div class="mx-auto my-auto col-4">
    <% if end_user_signed_in? %>
      <p class="my-auto header_name text-right"><b>ようこそ、<%= end_user.name %>さん！</b></p>
      <% else %>
    <% end %>
  </div>
  <!--リンク-->
  <nav class="navbar navbar-expand-lg">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon text-light"><i class="fa-solid fa-bars"></i></span>
  </button>
  <div class="collapse navbar-collapse row " id="navbarSupportedContent">
    <ul class="navbar-nav header-button">
      <% if request.fullpath.include? "/admin" %>
      <!-- adminログイン時のヘッダー -->
        <% if admin_signed_in? %>
          <li class="nav-item"><%= link_to "投稿一覧", admin_posts_path, class: "nav-link text-light" %></li>
          <li class="nav-item"><%= link_to "コメント一覧", admin_comments_path, class: "nav-link text-light" %></li>
          <li class="nav-item"><%= link_to "ユーザー一覧", admin_end_users_path, class: "nav-link text-light" %></li>
          <li class="nav-item"><%= link_to "タグ一覧", admin_tags_path, class: "nav-link text-light" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-light" %></li>
      <!-- adminログアウト時のヘッダー　-->
        <% else %>
          <li class="nav-item"><%= link_to "ログイン", new_admin_session_path, class: "nav-link text-light" %></li>
        <% end %>
      <% else %>
      <!-- end_userログイン時のヘッダー　-->
        <% if end_user_signed_in? %>
          <li class="nav-item"><%= link_to "マイページ", end_user_path(current_end_user.id), class:"nav-link text-light" %></li>
          <li class="nav-item"><%= link_to "投稿一覧", posts_path, class: "nav-link text-light" %></li>
          <li class="nav-item"><%= link_to "投稿フォーム", new_post_path, class: "nav-link text-light" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class: "nav-link text-light" %></li>
      <!-- end_userログアウト時のヘッダー　-->
        <% else %>
          <li class="nav-item"><%= link_to "ゲストログイン", end_users_guest_sign_in_path, class: "nav-link text-light", method: :post %></li>
          <li class="nav-item"><%= link_to "ログイン", new_end_user_session_path, class: "nav-link text-light" %></li>
          <li class="nav-item"><%= link_to "新規登録", new_end_user_registration_path, class: "nav-link text-light" %></li>
        <% end %>
       <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_post_form.html.erb
<!--投稿フォーム-->
<%= form_with model: post, local: true, multipart: true do |f| %>
  <div class="form-group">
    <%= f.label :タイトル %>
    <%= f.text_field :title, class: 'form-control post_title' %>
  </div>
  <div class="tag_form">
    <label>タグ(,で区切ると複数タグ登録できます)</label>
    <%= f.text_field :tag_name,value: @tag_list, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :本文 %>
    <%= f.text_area :body, class: 'form-control post_body', rows:"5" %>
  </div>

  <div>
    <%= f.label :画像 %>
    <%= f.file_field :images, multiple: true, accept: "image/*" %>
    <% if post.images.attached? %>
    <p>選択済みの画像（削除する画像にチェックをつけてください）</p>
    <div class="d-flex" style="flex-wrap:wrap;">
    <% @post.images.each do |image| %>
      <div>
        <%= f.check_box :image_ids, { multiple: true }, image.id, false %>
        <label for="post_image_ids_<%= image.id %>" > 
          <%= image_tag image, size: '180x120' %>
        </label>
      </div>
    <% end %>
    </div>
  <% end %>
  </div>

  <div class="form-group mt-3">
    <%= f.submit "登録する", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/layouts/_post_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>ユーザー</th>
      <th>タイトル</th>
      <th>タグ</th>
      <th>画像</th>
    </tr>
  </thead>
  <tbody>
    <% posts.each do |post| %>
    <tr>
      <td><%= link_to(post.end_user) do %>
        <%= image_tag post.end_user.get_profile_image, size:'50x50' %>
         <% end %>
      </td>
      <td><%= link_to post.title,post, class: "post_#{post.id}" %></td>
      <td>
        <% post.tags.each do |tag| %>
          <i class="fa-sharp fa-solid fa-tag"></i>
          <%= tag.tag_name %>
        <% end %>
      </td>
      <td><%= post.images.attached? ? post.images.count : 0 %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate posts %>

app/views/layouts/_post_show.html.erb
<table class='table'>
  <tr>
    <td>ユーザー</td>
    <td>
      <%= link_to(@post.end_user) do %>
        <%= image_tag @post.end_user.get_profile_image, size:"100x100" %><br>
        <%= @post.end_user.name %>
      <% end %>
    </td>
  </tr>
  <tr>
    <td>タイトル</td>
    <td><%= @post.title %></td>
  </tr>
  <tr>
    <td>タグ</td>
    <td>
      <% @post_and_tags.each do |tag| %>
      <i class="fa-sharp fa-solid fa-tag"></i>
      <%= tag.tag_name %>
      <% end %>
    </td>
  </tr>
  <tr>
    <td>本文</td>
    <td><%= @post.body %></td>
  </tr>
</table>

app/views/layouts/_search_form.html.erb
<div class="row justify-content-end">
  <!--管理者はユーザーを検索-->
  <% if admin_signed_in? %>
    <%= form_with url: admin_search_path,method: :get, local: true do |f| %>
      <%= f.text_field :word,placeholder:"ユーザー検索"%>
      <%= f.submit'検索'%>
    <% end %>
  <% else %>
  <!--ユーザーは投稿を検索-->
    <% if end_user_signed_in? %>
      <%= form_with url: search_path,method: :get, local: true do |f| %>
        <%= f.text_field :word,placeholder:"キーワード検索"%>
        <%= f.submit'検索'%>
      <% end %>
    <% end %>
  <!--未ログイン時は非表示-->
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aquariumate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/19a9241544.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Lightbox2(画像のポップアップ表示)-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
  </head>

  <body>
    <div class="all_contents">
      <header>
        <div><%= render 'layouts/header', end_user: current_end_user %></div>
      </header>
      <div class="search"><%= render 'layouts/search_form', end_user: current_end_user %></div>
      <main>
        <%= yield %>
      </main>
      <footer></footer>
    </div>
  </body>
</html>